# Generated by Django 6.0 on 2025-12-07 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='飲食店名')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
                ('referral_code', models.CharField(max_length=20, unique=True, verbose_name='紹介コード')),
                ('reward_per_customer', models.IntegerField(default=1000, verbose_name='1人あたりの報酬額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': 'パートナー（飲食店）',
                'verbose_name_plural': 'パートナー一覧',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お客様名')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='入会日時')),
                ('is_paid', models.BooleanField(default=False, verbose_name='報酬支払い済み')),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='referrals.partner', verbose_name='紹介元')),
            ],
            options={
                'verbose_name': 'お客様',
                'verbose_name_plural': 'お客様一覧',
            },
        ),
    ]
