# Generated by Django 5.2.8 on 2025-12-08 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_remove_customer_phone_number_alter_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店舗名')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗一覧',
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referrals.salon', verbose_name='紐付け店舗'),
        ),
    ]
