# Generated by Django 5.2.8 on 2025-12-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_salon_partner_salon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'パートナー', 'verbose_name_plural': 'パートナー一覧'},
        ),
        migrations.AddField(
            model_name='customer',
            name='has_visited',
            field=models.BooleanField(default=False, verbose_name='来店済み'),
        ),
    ]
